name: rni_app
description: "Frontend interface for Air Purifier device."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_animate: ^4.5.2
  fl_chart: ^1.1.1
  gap: ^3.0.1
  flutter_slidable: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true